import { ConversationState } from '../config/types';

/** Valid state transitions */
export const STATE_TRANSITIONS: Record<ConversationState, ConversationState[]> = {
  NEW: ['ACTIVE_QA', 'ORDER_INQUIRY', 'SHIPMENT_TRACKING', 'RETURN_REFUND', 'PRODUCT_INQUIRY', 'LEAD_QUALIFICATION', 'SUPPORT_TRIAGE', 'ESCALATED'],
  ACTIVE_QA: ['ORDER_INQUIRY', 'SHIPMENT_TRACKING', 'RETURN_REFUND', 'PRODUCT_INQUIRY', 'LEAD_QUALIFICATION', 'MEETING_BOOKING', 'SUPPORT_TRIAGE', 'ESCALATED', 'RESOLVED'],
  ORDER_INQUIRY: ['ACTIVE_QA', 'SHIPMENT_TRACKING', 'RETURN_REFUND', 'SUPPORT_TRIAGE', 'ESCALATED', 'RESOLVED'],
  SHIPMENT_TRACKING: ['ACTIVE_QA', 'ORDER_INQUIRY', 'RETURN_REFUND', 'SUPPORT_TRIAGE', 'ESCALATED', 'RESOLVED'],
  RETURN_REFUND: ['ACTIVE_QA', 'ORDER_INQUIRY', 'SHIPMENT_TRACKING', 'SUPPORT_TRIAGE', 'ESCALATED', 'RESOLVED'],
  PRODUCT_INQUIRY: ['ACTIVE_QA', 'ORDER_INQUIRY', 'LEAD_QUALIFICATION', 'SUPPORT_TRIAGE', 'ESCALATED', 'RESOLVED'],
  LEAD_QUALIFICATION: ['ACTIVE_QA', 'MEETING_BOOKING', 'PRODUCT_INQUIRY', 'SUPPORT_TRIAGE', 'ESCALATED', 'RESOLVED'],
  MEETING_BOOKING: ['ACTIVE_QA', 'LEAD_QUALIFICATION', 'ESCALATED', 'RESOLVED'],
  SUPPORT_TRIAGE: ['ACTIVE_QA', 'ORDER_INQUIRY', 'RETURN_REFUND', 'ESCALATED', 'RESOLVED'],
  ESCALATED: ['RESOLVED'],
  RESOLVED: ['ACTIVE_QA', 'ORDER_INQUIRY'], // can reopen
};

/** State transition event */
export interface StateTransitionEvent {
  conversationId: string;
  from: ConversationState;
  to: ConversationState;
  reason: string;
  timestamp: number;
}
