import client from 'prom-client';

// Collect default Node.js metrics
client.collectDefaultMetrics({ prefix: 'zobot_' });

export const httpRequestDuration = new client.Histogram({
  name: 'zobot_http_request_duration_seconds',
  help: 'Duration of HTTP requests in seconds',
  labelNames: ['method', 'route', 'status_code'] as const,
  buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],
});

export const messagesProcessed = new client.Counter({
  name: 'zobot_messages_processed_total',
  help: 'Total messages processed',
  labelNames: ['channel', 'tenant'] as const,
});

export const llmRequestDuration = new client.Histogram({
  name: 'zobot_llm_request_duration_seconds',
  help: 'Duration of LLM API calls',
  labelNames: ['provider', 'model', 'status'] as const,
  buckets: [0.5, 1, 2, 5, 10, 30],
});

export const toolCallDuration = new client.Histogram({
  name: 'zobot_tool_call_duration_seconds',
  help: 'Duration of tool executions',
  labelNames: ['tool', 'version', 'status'] as const,
  buckets: [0.01, 0.05, 0.1, 0.5, 1, 5],
});

export const ticketOperations = new client.Counter({
  name: 'zobot_ticket_operations_total',
  help: 'Total ticket create/update operations',
  labelNames: ['operation', 'status'] as const,
});

export const escalations = new client.Counter({
  name: 'zobot_escalations_total',
  help: 'Total escalations to human',
  labelNames: ['reason', 'channel'] as const,
});

export const stateTransitions = new client.Counter({
  name: 'zobot_state_transitions_total',
  help: 'Conversation state transitions',
  labelNames: ['from', 'to'] as const,
});

export const activeConversations = new client.Gauge({
  name: 'zobot_active_conversations',
  help: 'Number of active conversations',
  labelNames: ['channel'] as const,
});

// ───── Multi-LLM Metrics ─────────────────────────────────────────

export const llmProviderFailovers = new client.Counter({
  name: 'zobot_llm_provider_failovers_total',
  help: 'Count of failovers from one LLM provider to another',
  labelNames: ['from_provider', 'to_provider', 'reason'] as const,
});

export const llmTokenUsage = new client.Counter({
  name: 'zobot_llm_token_usage_total',
  help: 'Total tokens used across LLM providers',
  labelNames: ['provider', 'model', 'token_type'] as const,
});

// ───── Learning Pipeline Metrics ─────────────────────────────────

export const learningPipelineRuns = new client.Counter({
  name: 'zobot_learning_pipeline_runs_total',
  help: 'Total learning pipeline executions',
  labelNames: ['status'] as const,
});

export const learningPipelineDuration = new client.Histogram({
  name: 'zobot_learning_pipeline_duration_seconds',
  help: 'Duration of learning pipeline runs',
  buckets: [1, 5, 10, 30, 60, 120, 300],
});

export const learningArtifactsGenerated = new client.Counter({
  name: 'zobot_learning_artifacts_generated_total',
  help: 'Total learning artifacts generated by type',
  labelNames: ['type'] as const,
});

export const faqCandidatesPending = new client.Gauge({
  name: 'zobot_faq_candidates_pending',
  help: 'Number of pending FAQ candidates awaiting review',
});

export const botResolutionRate = new client.Gauge({
  name: 'zobot_bot_resolution_rate',
  help: 'Percentage of conversations resolved without escalation',
  labelNames: ['provider', 'model', 'prompt_version'] as const,
});

// ───── Chat Session Metrics ──────────────────────────────────────

export const chatSessionsCreated = new client.Counter({
  name: 'zobot_chat_sessions_created_total',
  help: 'Total chat sessions created',
  labelNames: ['channel'] as const,
});

export const chatSessionsEnded = new client.Counter({
  name: 'zobot_chat_sessions_ended_total',
  help: 'Total chat sessions ended',
  labelNames: ['ended_by'] as const,
});

export const csatSubmissions = new client.Counter({
  name: 'zobot_csat_submissions_total',
  help: 'Total CSAT survey submissions',
});

export const csatAverageRating = new client.Gauge({
  name: 'zobot_csat_average_rating',
  help: 'Running average CSAT rating (1-5)',
});

export const fileUploads = new client.Counter({
  name: 'zobot_file_uploads_total',
  help: 'Total file uploads',
  labelNames: ['mimeType'] as const,
});

// ───── VOC Intelligence Metrics ─────────────────────────────────

export const vocPreprocessDuration = new client.Histogram({
  name: 'zobot_voc_preprocess_duration_seconds',
  help: 'Duration of VOC pre-processor execution',
  buckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1],
});

export const vocSentimentDistribution = new client.Counter({
  name: 'zobot_voc_sentiment_total',
  help: 'Distribution of detected sentiment labels',
  labelNames: ['label', 'emotion'] as const,
});

export const vocUrgencyDistribution = new client.Counter({
  name: 'zobot_voc_urgency_total',
  help: 'Distribution of detected urgency levels',
  labelNames: ['level'] as const,
});

export const vocLanguageDistribution = new client.Counter({
  name: 'zobot_voc_language_total',
  help: 'Distribution of detected languages',
  labelNames: ['language'] as const,
});

export const vocIntentConfidence = new client.Histogram({
  name: 'zobot_voc_intent_confidence',
  help: 'Distribution of LLM intent confidence scores',
  buckets: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
});

export const vocRiskFlags = new client.Counter({
  name: 'zobot_voc_risk_flags_total',
  help: 'Count of risk flags detected',
  labelNames: ['type'] as const,
});

export const vocFCRRate = new client.Gauge({
  name: 'zobot_voc_fcr_rate',
  help: 'First Contact Resolution rate (rolling)',
});

export const vocResolutionReceipts = new client.Counter({
  name: 'zobot_voc_resolution_receipts_total',
  help: 'Count of responses that included a resolution receipt',
});

// ───── Tool Runtime Hardening Metrics ───────────────────────────

export const toolRetries = new client.Counter({
  name: 'zobot_tool_retries_total',
  help: 'Count of tool execution retries',
  labelNames: ['tool'] as const,
});

export const toolOutputValidationFailures = new client.Counter({
  name: 'zobot_tool_output_validation_failures_total',
  help: 'Count of tool output schema validation failures',
  labelNames: ['tool'] as const,
});

// ───── Proactive Support Metrics ────────────────────────────────

export const proactiveAlertsGenerated = new client.Counter({
  name: 'zobot_proactive_alerts_generated_total',
  help: 'Count of proactive support alerts generated',
  labelNames: ['type'] as const,
});

// ───── PII Governance Metrics ──────────────────────────────────

export const piiDetections = new client.Counter({
  name: 'zobot_pii_detections_total',
  help: 'Count of PII instances detected',
  labelNames: ['type', 'severity'] as const,
});

export const piiTokenizations = new client.Counter({
  name: 'zobot_pii_tokenizations_total',
  help: 'Count of PII values tokenized',
  labelNames: ['type', 'severity'] as const,
});

export const piiPurges = new client.Counter({
  name: 'zobot_pii_purges_total',
  help: 'Count of PII purge operations',
  labelNames: ['trigger'] as const,
});

// ───── Enhancement v2: Webhook Dedup Metrics ────────────────────

export const webhookDuplicatesTotal = new client.Counter({
  name: 'zobot_webhook_duplicates_total',
  help: 'Count of duplicate webhook messages blocked',
});

// ───── Enhancement v2: Cache Metrics ────────────────────────────

export const cacheHitsTotal = new client.Counter({
  name: 'zobot_cache_hits_total',
  help: 'Total cache hits',
  labelNames: ['cache_type'] as const,
});

export const cacheMissesTotal = new client.Counter({
  name: 'zobot_cache_misses_total',
  help: 'Total cache misses',
  labelNames: ['cache_type'] as const,
});

// ───── Enhancement v2: Dependency Health Metrics ────────────────

export const dependencyStatus = new client.Gauge({
  name: 'zobot_dependency_status',
  help: 'Dependency health status (1=healthy, 0.5=degraded, 0=down)',
  labelNames: ['dependency'] as const,
});

export const fallbackResponsesTotal = new client.Counter({
  name: 'zobot_fallback_responses_total',
  help: 'Count of fallback responses served',
  labelNames: ['intent'] as const,
});

// ───── Enhancement v2: Co-Pilot Metrics ─────────────────────────

export const copilotSuggestionsTotal = new client.Counter({
  name: 'zobot_copilot_suggestions_total',
  help: 'Total co-pilot suggestions generated',
  labelNames: ['type'] as const,
});

export const copilotAcceptanceRate = new client.Gauge({
  name: 'zobot_copilot_acceptance_rate',
  help: 'Co-pilot suggestion acceptance rate',
});

// ───── Enhancement v2: SLA Metrics ──────────────────────────────

export const slaComplianceRate = new client.Gauge({
  name: 'zobot_sla_compliance_rate',
  help: 'SLA compliance rate (percentage)',
  labelNames: ['tier'] as const,
});

export const slaBreachTotal = new client.Counter({
  name: 'zobot_sla_breach_total',
  help: 'Total SLA breaches',
  labelNames: ['tier', 'type'] as const,
});

export const slaTtfrSeconds = new client.Histogram({
  name: 'zobot_sla_ttfr_seconds',
  help: 'Time to first response in seconds',
  labelNames: ['tier'] as const,
  buckets: [10, 30, 60, 120, 300, 600],
});

// ───── Enhancement v2: Omnichannel Metrics ──────────────────────

export const crossChannelSwitchesTotal = new client.Counter({
  name: 'zobot_cross_channel_switches_total',
  help: 'Total cross-channel conversation switches',
  labelNames: ['from_channel', 'to_channel'] as const,
});

// ───── Enhancement v2: Audit Metrics ────────────────────────────

export const auditEventsTotal = new client.Counter({
  name: 'zobot_audit_events_total',
  help: 'Total audit events logged',
  labelNames: ['category'] as const,
});

// ───── Enhancement v2: Experiment Metrics ───────────────────────

export const experimentAssignmentsTotal = new client.Counter({
  name: 'zobot_experiment_assignments_total',
  help: 'Total experiment variant assignments',
  labelNames: ['experiment', 'variant'] as const,
});

// ───── Enhancement v2: Outbound Metrics ─────────────────────────

export const outboundMessagesTotal = new client.Counter({
  name: 'zobot_outbound_messages_total',
  help: 'Total outbound proactive messages',
  labelNames: ['trigger_type', 'status'] as const,
});

// ───── Enhancement v2: Routing Metrics ──────────────────────────

export const routingDecisionsTotal = new client.Counter({
  name: 'zobot_routing_decisions_total',
  help: 'Total intelligent routing decisions',
  labelNames: ['strategy', 'reason'] as const,
});

// ───── Enhancement v2: Incident Metrics ─────────────────────────

export const activeIncidents = new client.Gauge({
  name: 'zobot_active_incidents',
  help: 'Number of active incidents',
  labelNames: ['severity'] as const,
});

export async function getMetrics(): Promise<string> {
  return client.register.metrics();
}

export function getContentType(): string {
  return client.register.contentType;
}
